version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
  
  tests:
    build: .
    command: ["pytest", "--maxfail=5", "--disable-warnings", "-q", "-v"]
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - web  # Espera a que el contenedor 'web' esté listo
